# Generated by Django 5.1.3 on 2024-11-15 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_tipolocal'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalComercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='locales_comerciales/')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ciudad')),
                ('tipo_local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.tipolocal')),
            ],
        ),
    ]
